#!/usr/bin/env bash

set -e # exit script if any error is encountered

usage() {
cat <<- _EOF_ 
Usage: scriptify [OPTIONS...] [-f [FILE]] -- command

Create a file and make it executable and open the file in your preferred text editior

Examples
--------
scriptify -f foo.sh           create a script called foo.sh
scritptify -fn bar.sh         create a file called bar.sh and open it in neovim
scriptify -fv foobar.sh       create a file called foobar.sh and open it in vscodium

Options:
--------
  -f, --file <name>           specify the name of the file to create
  

  -h, --help                  show help message

  -n, --nvim                  open the script in neovim
  -v, --vscodium              open the script in vscodium
_EOF_

  return
}

create_file () {
  if [[ -e "$1" ]]; then
  # file already exists
    declare -l $REPLY # force the reply to become lowercase to add it to the options
    echo "File exists, overwrite? y/n"
    read

    case $REPLY in
    yes | y)       echo "" > "$1"
                   ;;
    no | n)        exit
                   ;;
    *)             exit 1
                   ;;
    esac
  else
    touch "$1" && chmod u+rx "$1" && echo '#!/usr/bin/env bash' > "$1"
  fi
}

while [[ -n "$1" ]]; do
  case "$1" in
     -f | --file)      shift
                           # When the file does not exists check for other arguments
                           if [[ -n "$1" ]]; then
                             case "$1" in
                               -n | --nvim )    shift
                                                create_file "$1" && nvim "$1"
                                                ;;
                               -v | --code )    shift
                                                create_file "$1" && vscodium "$1"
                                                ;;
                                *)              create_file "$1"
                                                ;;
                             esac
                           else
                             usage
                           fi
                       exit
                       ;;
     -fn | -nf)        shift
                       if [[ -n "$1" ]]; then
                        create_file "$1" && nvim "$1"
                        exit
                       fi
                       ;;
     -fv | -vf)        shift
                       if [[ -n "$1" ]]; then
                        create_file "$1" && vscodium "$1"
                        exit
                       fi
                       ;;
     -h | --help)      usage
                       ;;
     *)                usage >&2
                       exit 1
                       ;;
   esac
   shift # Advance the positional parameters to ensure the loop eventually terminates (makes the while loop test fail)
done
