#!/usr/bin/env bash

set -e # exit script if any error is encountered

help() {
cat <<- _EOF_ 
Usage: scriptify [OPTIONS...] [-f [FILE]] [-m [mode]] -- command

Create a file and make it executable and further open the file in your preferred text editior

tl;dr:
  scriptify -f foo.sh                       create a script called foo.sh
  scriptify -f bar.sh -e nvim               create a script called bar.sh and open it in neovim
  scriptify -f foobar.sh -e vscodium        create a script called foobar.sh and open it in vscodium
  scritiify -f foo.sh -d                    create a script called foo.sh and open it using the default editor i.e. \$EDITOR

Options:
  -f, --filename                specify the name of the script to create
  -h, --help                    show help message
  -e, --editor                  preferred editor, one of: nvim, code, vscodium 
  -d, --default-editor          open in default editor i.e. \$EDITOR  

Editor:
  nvim              open the script in neovim
  code              open the file in vscode
  vscodium          open the file in vscodium
  
_EOF_
}

parse_editor() {
  case "$1" in
    nvim)
      nvim "$FILENAME"
      ;;
    vscodium)
      vscodium "$FILENAME"
      ;;
    code)
      code "$FILENAME"
      ;;
    zed)
      zed "$FILENAME"
      ;;
    *)
      exit
      ;;
  esac
}

define_editor_env() {
  echo "" >> ~/.profile # Add a newline
  echo '# Add default editor' >> ~/.profile # Add a comment
  echo "export EDITOR=$REPLY" >> ~/.profile
  source ~/.profile
}

use_def_editor() {
  local default_editor=$(echo $EDITOR)

  if [[ $default_editor == "" ]]; then
    declare -l $REPLY
    echo "Set default editor [nvim, code, vscodium,...]"
    read
    define_editor_env "$REPLY"
    "$REPLY" "$FILENAME"
  else
    echo "You have a default editor"
  fi
}

create_file() {
  if [[ -e "$1" ]]; then
  # file already exists
    declare -l $REPLY # force the reply to become lowercase to add it to the options
    echo "File exists, overwrite? y/n"
    read

    case $REPLY in
    yes | y)       
      echo "" > "$1" && echo '#!/usr/bin/env bash' > "$1" 
      ;;
    no | n)        
      exit
      ;;
    *)             
      exit 1
      ;;
    esac
  else
    touch "$1" && chmod u+rx "$1" && echo '#!/usr/bin/env bash' > "$1"
  fi
}

parse_args() {
  local options=$(getopt -o hf:de: --longoptions help,file:,default-editor,editor: -- "$@")
  eval set -- "$options"
  
  while true; do
    case "$1" in
      -f | --filename)
        shift
        FILENAME="$1"
        create_file "$1" 
        ;;  
      -h | --help)
        help 
        exit
        ;;  
      -e | --editor)
        shift
        parse_editor "$1"
        ;;
      -d | --default-editor)
        use_def_editor "$FILENAME"
        ;;
      --)
        break
        ;;
    esac
    shift
  done
}

if [[ -z "$1" ]]; then
  help
  exit
fi

parse_args "$@" # Parse the arguments 